/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Barang;

import Dashboard.Dashboard;
import java.sql.*;
import javax.swing.table.*;
import javax.swing.JOptionPane;
import Login.*;


/**
 *
 * @author Edwin
 */
public class FormBarang extends javax.swing.JFrame {

    /**
     * Creates new form Form_Stok_Barang
     */
    public FormBarang() {
        initComponents();
        tampilkanStokBarang();
        setSize(1366, 768); // Atur ukuran manual
        setLocationRelativeTo(null); // Pusat layar
        setVisible(true); // Penting kalau di luar main()
    }

    private void tampilkanStokBarang() {
        try {
            Connection conn = Login.DatabaseConnection.connect();
            String sql = "SELECT id_barang, kode_barang, nama_barang, kategori, satuan, harga_beli, harga_jual, stok FROM stok_barang";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = new DefaultTableModel();
            model = new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("Kode Barang");
            model.addColumn("Nama Barang");
            model.addColumn("Kategori");
            model.addColumn("Satuan");
            model.addColumn("Harga Beli");
            model.addColumn("Harga Jual");
            model.addColumn("Stok");
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_barang"),
                    rs.getString("kode_barang"),
                    rs.getString("nama_barang"),
                    rs.getString("kategori"),
                    rs.getString("satuan"),
                    rs.getDouble("harga_beli"),
                    rs.getDouble("harga_jual"),
                    rs.getInt("stok")
                });
            }
            jTable1.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private void bersihkanForm() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jComboBox2.setSelectedIndex(-1);
        jComboBox1.setSelectedIndex(-1);
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
    }

    private boolean validasiInput() {
        if (jTextField2.getText().isEmpty() || jTextField3.getText().isEmpty()
                || jTextField4.getText().isEmpty() || jTextField5.getText().isEmpty()
                || jTextField6.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 48)); // NOI18N
        jLabel1.setText("STOK BARANG");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(510, 40, 360, 60);

        jLabel2.setText("ID BARANG ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(31, 141, 116, 26);

        jLabel3.setText("KODE BARANG");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(34, 185, 140, 26);

        jLabel4.setText("NAMA BARANG");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(31, 229, 143, 26);

        jLabel5.setText("KATEGORI");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(31, 279, 99, 26);

        jLabel6.setText("SATUAN");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(31, 333, 78, 26);

        jLabel7.setText("HARGA BELI ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(31, 380, 124, 26);

        jLabel8.setText("HARGA JUAL");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(35, 433, 120, 26);

        jLabel9.setText("STOK BARANG");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(35, 486, 138, 26);

        jLabel10.setText("SEARCH ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(720, 140, 84, 26);

        jButton1.setText("SIMPAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 530, 170, 35);

        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 530, 160, 35);

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(545, 530, 140, 35);

        jButton4.setText("SEARCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1090, 180, 140, 35);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(190, 138, 497, 32);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(190, 182, 497, 32);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(190, 226, 497, 32);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(190, 377, 497, 32);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(190, 430, 497, 32);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(190, 483, 497, 32);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(820, 140, 410, 32);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pcs", "Kg", "Liter", "Box", "Pack" }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(190, 327, 497, 32);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(710, 240, 520, 320);

        jButton5.setText("DASHBOARD");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1040, 580, 190, 35);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Makanan", "Minuman", "Lainnya" }));
        jComboBox2.setSelectedIndex(-1);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(190, 270, 500, 32);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Downloads\\Desain tanpa judul.png")); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(-3, 0, 1330, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if (!validasiInput()) {
            return;
        }

        try (Connection conn = DatabaseConnection.connect()) {
            String sql = "INSERT INTO stok_barang (kode_barang, nama_barang, kategori, satuan, harga_beli, harga_jual, stok) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, jTextField2.getText());
            pstmt.setString(2, jTextField3.getText());
            pstmt.setString(3, jComboBox2.getSelectedItem().toString());
            pstmt.setString(4, jComboBox1.getSelectedItem().toString());
            pstmt.setDouble(5, Double.parseDouble(jTextField4.getText()));
            pstmt.setDouble(6, Double.parseDouble(jTextField5.getText()));
            pstmt.setInt(7, Integer.parseInt(jTextField6.getText()));

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
            tampilkanStokBarang();
            bersihkanForm();
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!validasiInput() || jTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan diedit terlebih dahulu!");
            return;
        }

        try (Connection conn = DatabaseConnection.connect()) {
            String sql = "UPDATE stok_barang SET kode_barang=?, nama_barang=?, kategori=?, satuan=?, "
                    + "harga_beli=?, harga_jual=?, stok=? WHERE id_barang=?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, jTextField2.getText());
            pstmt.setString(2, jTextField3.getText());
            pstmt.setString(3, jComboBox2.getSelectedItem().toString());
            pstmt.setString(4, jComboBox1.getSelectedItem().toString());
            pstmt.setDouble(5, Double.parseDouble(jTextField4.getText()));
            pstmt.setDouble(6, Double.parseDouble(jTextField5.getText()));
            pstmt.setInt(7, Integer.parseInt(jTextField6.getText()));
            pstmt.setInt(8, Integer.parseInt(jTextField1.getText()));

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
            tampilkanStokBarang();
            bersihkanForm();
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String keyword = jTextField7.getText().trim();

if (keyword.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Masukkan nama atau kode barang yang ingin dicari.");
    return;
}

DefaultTableModel model = new DefaultTableModel(
    new Object[]{"ID", "Kode Barang", "Nama Barang", "Kategori", "Satuan", "Harga Beli", "Harga Jual", "Stok"}, 0) {
    @Override
    public boolean isCellEditable(int row, int column) {
        return false;
    }
};

try (Connection conn = DatabaseConnection.connect();
     PreparedStatement stmt = conn.prepareStatement(
         "SELECT * FROM stok_barang WHERE nama_barang LIKE ? OR kode_barang LIKE ?")) {

    stmt.setString(1, "%" + keyword + "%");
    stmt.setString(2, "%" + keyword + "%");

    ResultSet rs = stmt.executeQuery();

    while (rs.next()) {
        model.addRow(new Object[]{
            rs.getInt("id_barang"),
            rs.getString("kode_barang"),
            rs.getString("nama_barang"),
            rs.getString("kategori"),
            rs.getString("satuan"),
            rs.getString("harga_beli"),
            rs.getString("harga_jual"),
            rs.getString("stok")
        });
    }

    jTable1.setModel(model);

    if (model.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "Barang tidak ditemukan.");
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mencari: " + e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if (jTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus terlebih dahulu!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try (Connection conn = DatabaseConnection.connect()){
                String sql = "DELETE FROM stok_barang WHERE id_barang=?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1, Integer.parseInt(jTextField1.getText()));
                pstmt.executeUpdate();

                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                tampilkanStokBarang();
                bersihkanForm();
            } catch (SQLException | NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
int selectedRow = jTable1.getSelectedRow();

        // Mengisi field dengan data dari tabel
        if (selectedRow != -1) {
            jTextField1.setText(jTable1.getValueAt(selectedRow, 0).toString()); // ID Barang
            jTextField2.setText(jTable1.getValueAt(selectedRow, 1).toString()); // Kode Barang
            jTextField3.setText(jTable1.getValueAt(selectedRow, 2).toString()); // Nama Barang
            jComboBox2.setSelectedItem(jTable1.getValueAt(selectedRow, 3).toString()); // Kategori
            jComboBox1.setSelectedItem(jTable1.getValueAt(selectedRow, 4).toString()); // Satuan
            jTextField4.setText(jTable1.getValueAt(selectedRow, 5).toString()); // Harga Beli
            jTextField5.setText(jTable1.getValueAt(selectedRow, 6).toString()); // Harga Jual
            jTextField6.setText(jTable1.getValueAt(selectedRow, 7).toString()); // Stok
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    new Dashboard().setVisible(true);   
    dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
